---
title: "Human behavioral biology"
author: "yalisa"
date: "31 03 2020"
output: html_document

bibliograpy: sapolsky.bib
link-citations: yes
csl: gost-r-7-0-5-2008-numeric-iaa.csl
biblio-style: numeric
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- Spring 2010 
https://www.youtube.com/watch?v=NNnIGh9g6fA&list=PL848F2368C90DDC3D
-->

# 1. Introduction to Human Behavioral Biology

> "Искать биологическое объяснение человеческому поведению трудоемкий процесс"

Мыслить категориями. Континуум разбивается на категории. 

NB! мышление категориями также и ограничивает.

В некоторых областях создаются категории для понятий, которым категории совсем не свойственны. Пример: континуум света, изменяющая длинна волны от фиолетового до красного и бесконечное количество вариантов между ними.  

Континуум разбивается на категории, потому что так проще хранить информацию.То на какие категории разбивается континуум зависит от языка.  

> Рассуждение категориями позволяет запоминать и оценивать вещи.

Проблемы категориального мышления:

1. Если сильно зацикливаться на категориях, то можно не заметить разницу между объектами, которые в нее попали.

2. Проводя границу между категориями можно не заметить, насколько похоже то что находится по обе стороны от нее (незначительная разница приобретает субъективную значимость).

3. Если обращать слишком много внимания на рамки -- не видишь общую картину (видишь только категории).

Недооценка различия вещей попавших в одну категорию
Переоценка различия между тем, что находится по разные стороны границы 
Зацикливание на границах категорий -- стирает общую картину
<!-- (Когда вы зацикливаетесь на границах категорий, то не видите обей картины) -->

Цель курса -- изучение глобального сложного процесса биологии поведения, избегая категориального мышления.


-- Зачем курица перешла дорогу?

Эндокринолог: ...уровень эстрогена в крови делает гипоталамус чувствительным к стимулам...

Анатом (биомеханик): ..ось "таза" курицы позволяет ей бегать...

Эволюционный биолог: ...тысячелетиями курицы не реагировавшие на сексуальные действия петухов оставляли меньше копий своих генов...

Все эти интерпретации -- разные категории, которые мы используем объясняя события. Все это разные рамки. Рамки из-за которых возникают проблемы: сложно понять насколько различны или похожи факты, сложно увидеть полную картину, легко переоценить важность рамок внутри которых живешь. 

Когда начинает казаться, что все что касается поведения можно объяснить только генами, только нейромедиаторами, ...

Как то, что происходит в теле влияет на эмоции, память и поведение. И как это влияет на организм. 


Для каждого типа поведения, во-первых посмотреть на его внешнее проявление (требуется много объективности). Затем, спросить, что происходило в организме за говение до этого действия, что могло вызвать это поведение, что происходит в мире нейронов ("ага!, такое поведение возникает из-за активности этой зоны мозга"). Еще шаг назад. Какой запах, звук или сенсорный стимул в окружающей среде стимулировал те нейроны, чья активация привела к этому поведению. Затем еще шаг назад, что на счет гормонов и их концентрации в крови за последние часы, как эти гормоны могли повлиять на восприятие стимулов? Продолжаем идти назад, вплоть до раннего развития и внутриутробного периода, генетического строения особи, генетического строения популяции, эволюционного давления... 

Как объясняется данные поведение в контексте каждого шага, и почем это не отдельные шаги, а способы выражения одних и тех же биологических факторов влияния.


Рамки следует воспринимать лишь как место из которого на данном этапе очень удобно объяснять все факторы влияния что шли до этого. С этой точки зрения таких рамок нет, есть лишь временная платформа. Просто удобный способ отследить то что происходило, начиная с млн лет эволюции. 


3 интеллектуальные проблемы (при изучении поведения):

1. Распознать обстоятельства, при которых в человеке нет ничего особенного (Человек такое же животное как и все остальные).

2. В человеке есть что-то общее с другими животными, но он используем это совсем по-другому. Физиология человека может быть скучной и обычной, но мы пользуемся ей так, как ни одно животное больше не может.  

3. Человек делает что-то, что даже близко не делает ни одно животное. 


> Основная стратегия курса -- сопротивляться категориальному мышлению 


> Мы должны воспринимать себя как ничем не примечательный вид, такой же как и другие виды, с той же самой скучной физиологией, которую мы при этом, используем совсем иначе. Мы вид совершающий поступки не имеющие аналогов в животном мире, которым мы должны найти биологическое объяснение.


Вводная часть -- знакомство с  категориями: теория эволюции, влияние молекулярной генетики на поведение, генетика поведения, этология, нейроанатомия, эндокринология.

2 половина курса -- рассмотрение конкретных примеров поведения, с разрушением рамок (что случилось а секунду, в мире нейронов, какой сенсорный стимул активировал эти нейроны..., до вопросов эволюции).

<!-- (
Каждую неделю дополнительное занятие, по объяснению базы!
На листах что я раздал много терминов, если вы не уверены что знакомы со всеми из них -- знак, что стоит посетить дополнительные лекции.
) -->

> Мы постоянно применяем биологию поведения, так что не плохо было бы ее еще и выучить.


<!-- Мои рабочие часы на листах. Перерывы ... если не забуду, в середине лекции, на 5 минут.  -->


Надо прочитать -- [@глейк2001хаос] -- способ изучения биологии не прибегающий к редукционизму.
Редукционизм не подходит для изучения поведения. Книга формирует мышление о науке. 

# 2. Behavioral Evolution
<!-- 31 марта 2010 -->
<!-- 21.02.2020 -->

Пара черепов... По черепу многое можно определить. 

"Разве природа не поразительна?" -- Нет!

Существует внутреняя логика в том как организмы функционируют, как они устроены, как они эволюционировали пытаяь найти оптимальное решение. 

Логику эволюционного развития можно применить и вдругой области и объяснить различные аспекты социалного поведения. 

Оптимизация... Оптимальная стратегияю. 



# 3. Behavioral Evolution II

# 4. Molecular Genetics I

# 5. Molecular Genetics II

# 6. Behavioral Genetics I

# 7. Behavioral Genetics II

# 8. Recognizing Relatives

# 9. Ethology

# 10. Introduction to Neuroscience I

# 11. Introduction to Neuroscience II

# 12. Endocrinology

# 13. Advanced Neurology and Endocrinology

# 14. Limbic System

# 15. Human Sexual Behavior I

# 16. Human Sexual Behavior II

# 17. Human Sexual Behavior III & Aggression I

# 18. Aggression II

# 19. Aggression III

# 20. Aggression IV

# 21. Chaos and Reductionism

# 22. Emergence and Complexity

# 23. Language

# 24. Schizophrenia

# 25. Individual Differences





# Литература









